language: php

php: 
 - 5.3

env:
 - TESTDB=SQLITE

before_script:
 - pear install pear/PHP_CodeSniffer
 - phpenv rehash
 - ./tests/travis/before.php --target ~/builds/ss --version="dev-master" --installer="master"
 - cd ~/builds/ss

script: 
 - sh -c "if [ '$PHPCS' != '1' ]; then phpunit -c phpunit.xml.dist; else phpcs --encoding=utf-8 --tab-width=4 --standard=framework/tests/phpcs/ruleset.xml -np framework && phpcs --encoding=utf-8 --standard=framework/tests/phpcs/tabs.xml -np framework; fi"

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - translation-staging
